#!/bin/bash
set -e

# Install Ax-shell
curl -fsSL get.axeni.de/ax-shell | bash

# Upgrade hyprland config
sed -i "/^autogenerated = 1.*/d" "$HOME"/.config/hypr/hyprland.conf
sed -i "s/^\$terminal =.*/\$terminal = alacritty/" "$HOME"/.config/hypr/hyprland.conf
sed -i "s/^\$fileManager =.*/\$fileManager = nautilus/" "$HOME"/.config/hypr/hyprland.conf
sed -i "/^\$menu =.*/d" "$HOME"/.config/hypr/hyprland.conf
sed -i "s/kb_layout.*/kb_layout = us, ru/" "$HOME"/.config/hypr/hyprland.conf
sed -i "s/kb_options.*/kb_options = grp:win_space_toggle/" "$HOME"/.config/hypr/hyprland.conf
sed -i "s/^bind.*\$terminal/bind = \$mainMod, Return, exec, \$terminal/" "$HOME"/.config/hypr/hyprland.conf
sed -i "/^bind.*\$menu/d" "$HOME"/.config/hypr/hyprland.conf
